App:
  NavTitle: 4th Printing (Work in Progress)
  NavTitleShort: 4th (WIP)
  NoItemsFound: No items found.
  NoRulesAvailable: No rules available.
  SearchPlaceholder: Search Rules
  Locale:
    ShowRules: Show Rules
    ShowFAQ: Show FAQ
    ShowErrata: Show Errata
  Titles:
    Search: Search Rules
  About:
    ModalTitle: Other Links
    CardLibrary: Card Library
    GitHub: GitHub
    Discord: Discord
    Support: Buried Giant Studios Support
